name: Github Actions MADE
run-name: Running System-Test
on:
  push:
    branches:
    - main
    paths:
    - 'project/**'

jobs:
  system-test-feedback:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Project Reps.
      uses: actions/checkout@v3
      with:
        path: project

    - name: Set python version 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
          pip install requests
          pip install pandas
    
    - name: Run test.sh
      working-directory: "project"
      run: |
          echo "> Check if directory project exists"
          ls project/test.sh
          echo "> Ensure file permission"
          chmod +x ./project/tests.sh
          sh ./test.sh
          echo "> Test Done!"
    



  
